### PR TITLE
Alex - review and approve!

### PR DESCRIPTION
**Pull request by Oleksandrozhoh**
public static void main(String[] args) {

        String str = "edisni egassem terceS", reversedStr = "";

        for (int i = str.length()-1; i >=0 ; i--) {
            reversedStr+=str.charAt(i);
        }

        System.out.println(reversedStr);
    }

### CODE REVIEW

**Comment by daurentk** [comment]
meaT,
RP s'xelA no tnemmoc dna weiver esaelp

**Comment by sayfulya** [comment]
OMG idk about u guys, but this push is the most valuable push out of all, made me almost cry! I swear! Merge it ASAP and clone it like million times so it doesn't get lost!

**Comment by KhrystynaN** [comment]
Wow Alex! Your story is great!

**Review by daurentk — APPROVED** [review]
Approved and merged to the master with eyes full of tears...

**Pull request merged**
