### PR TITLE
Elena branch

### PR DESCRIPTION
**Pull request by sayfulya**
Please review and let me know if I am doing it correct cause I am sooo lost with this GitHub (crying face)

### CODE REVIEW

**Comment by daurentk** [comment]
Team - please provide your comments (if any) to Lena's PR

**Comment by Oleksandrozhoh** [comment]
Ms. Elena has done a great job, files look good, thanks for your contribution!

**Comment by amirh3sam** [comment]
Ms. Elena you did awesome job! everything looks great!

**Comment by mengliiii** [comment]
Hey Elena, I reviewed already, everything looks great, congrats! Ready for merge!

**Review by daurentk — APPROVED** [review]

**Comment by daurentk** [comment]
Pull requests are approved for merging, taking into account all the feedback received from the scrum team

**Pull request merged**
